export const DEFAULT_NAVBAR_MENUS = [
  {
    label: "Home",
    url: "/",
    location: "navbar",
    menuType: "standard",
    order: 0,
    isActive: true,
    items: [],
    megaMenuPromo: {
      isEnabled: false,
      badge: "Featured",
      title: "",
      subtitle: "",
      imageUrl: "",
      link: "/",
    },
  },
  {
    label: "Collections",
    url: "/collections",
    location: "navbar",
    menuType: "mega_menu",
    order: 1,
    isActive: true,
    items: [
      { label: "Indoor Air Purifiers", url: "/collections/plant", group: "By Space" },
      { label: "Balcony & Sunlight Lovers", url: "/collections/plant", group: "By Space" },
      { label: "Low Maintenance Desktop", url: "/collections/plant", group: "By Space" },
      { label: "Living Room Floor Plants", url: "/collections/plant", group: "By Space" },
      { label: "Flowering & Exotic Foliage", url: "/collections/plant", group: "By Type" },
      { label: "Rare Botanical Aroids", url: "/collections/plant", group: "By Type" },
      { label: "Succulents & Hardy Cacti", url: "/collections/plant", group: "By Type" },
      { label: "Hanging Vines & Pothos", url: "/collections/plant", group: "By Type" },
      { label: "Artisanal Ceramic Pots", url: "/collections/tool", group: "Care Essentials" },
      { label: "Bio Vermicompost & Soil", url: "/collections/fertilizer", group: "Care Essentials" },
      { label: "Brass Misters & Pruners", url: "/collections/tool", group: "Care Essentials" },
      { label: "Organic Plant Vitamins", url: "/collections/fertilizer", group: "Care Essentials" },
    ],
    megaMenuPromo: {
      isEnabled: true,
      badge: "Featured Specimen",
      title: "Monstera & Tropical Living",
      subtitle: "Up to 25% Off Nursery Fresh Arrivals",
      imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=700&q=80",
      link: "/collections",
    },
  },
  {
    label: "Fertilizers",
    url: "/collections/fertilizer",
    location: "navbar",
    menuType: "dropdown",
    order: 2,
    isActive: true,
    items: [
      { label: "Organic Vermicompost", url: "/#products?category=fertilizer", group: "Soil Nutrition" },
      { label: "Bio Neem Cake & Protection", url: "/#products?category=fertilizer", group: "Soil Nutrition" },
      { label: "Liquid Seaweed Tonic", url: "/#products?category=fertilizer", group: "Foliar Sprays" },
      { label: "Slow Release Granules", url: "/#products?category=fertilizer", group: "Soil Nutrition" },
    ],
    megaMenuPromo: {
      isEnabled: false,
      badge: "Organic",
      title: "",
      subtitle: "",
      imageUrl: "",
      link: "/collections/fertilizer",
    },
  },
  {
    label: "About",
    url: "/about",
    location: "navbar",
    menuType: "standard",
    order: 3,
    isActive: true,
    items: [],
  },
  {
    label: "Contact",
    url: "/contact",
    location: "navbar",
    menuType: "standard",
    order: 4,
    isActive: true,
    items: [],
  },
];

export const DEFAULT_FOOTER_MENUS = [
  // Column: Shop
  {
    label: "Air Purifier Plants",
    url: "/collections/plant",
    location: "footer",
    footerColumn: "Shop",
    order: 0,
    isActive: true,
  },
  {
    label: "Indoor Foliage",
    url: "/collections/plant",
    location: "footer",
    footerColumn: "Shop",
    order: 1,
    isActive: true,
  },
  {
    label: "Organic Fertilizers",
    url: "/collections/fertilizer",
    location: "footer",
    footerColumn: "Shop",
    order: 2,
    isActive: true,
  },
  {
    label: "Pots & Planters",
    url: "/collections/tool",
    location: "footer",
    footerColumn: "Shop",
    order: 3,
    isActive: true,
  },

  // Column: Company
  {
    label: "About Us",
    url: "/about",
    location: "footer",
    footerColumn: "Company",
    order: 0,
    isActive: true,
  },
  {
    label: "Contact Nursery",
    url: "/contact",
    location: "footer",
    footerColumn: "Company",
    order: 1,
    isActive: true,
  },
  {
    label: "Plant Care Guides",
    url: "/#plant-care-guides",
    location: "footer",
    footerColumn: "Company",
    order: 2,
    isActive: true,
  },
  {
    label: "Today's Deals",
    url: "/#deals",
    location: "footer",
    footerColumn: "Company",
    order: 3,
    isActive: true,
  },

  // Column: Customer Service
  {
    label: "Track Your Order",
    url: "/track-order",
    location: "footer",
    footerColumn: "Customer Service",
    order: 0,
    isActive: true,
  },
  {
    label: "48-Hour Replacement",
    url: "/refund",
    location: "footer",
    footerColumn: "Customer Service",
    order: 1,
    isActive: true,
  },
  {
    label: "Delivery & Shipping",
    url: "/terms",
    location: "footer",
    footerColumn: "Customer Service",
    order: 2,
    isActive: true,
  },
  {
    label: "Wishlist",
    url: "/wishlist",
    location: "footer",
    footerColumn: "Customer Service",
    order: 3,
    isActive: true,
  },

  // Column: Legal
  {
    label: "Privacy Policy",
    url: "/privacy",
    location: "footer",
    footerColumn: "Legal",
    order: 0,
    isActive: true,
  },
  {
    label: "Terms & Conditions",
    url: "/terms",
    location: "footer",
    footerColumn: "Legal",
    order: 1,
    isActive: true,
  },
  {
    label: "Refund & Returns",
    url: "/refund",
    location: "footer",
    footerColumn: "Legal",
    order: 2,
    isActive: true,
  },
];

export const DEFAULT_ALL_MENUS = [...DEFAULT_NAVBAR_MENUS, ...DEFAULT_FOOTER_MENUS];
